### ISSUE TITLE
Deleted gist "disable subreddit css"

### ISSUE THREAD

**Issue by xHN35RQ** [nodiscc/scriptz#1]
I'm sorry, I deleted this gist ([disable subreddit css](https://gist.github.com/xHN35RQ/ee0bfd82f92d3cdf75a4)) before realizing you are referencing it. I've asked Github support to restore the gist, hopefully they can do so to enable you to fork it.

**Comment by xHN35RQ** [comment]
OK Github restored the gist, feel free to fork it if you want.

**Comment by nodiscc** [comment]
@xHN35RQ Thank you https://github.com/nodiscc/scriptz/blob/master/disable-subreddit-css.user.js
